/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miniproject;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FortuneTelling extends javax.swing.JFrame {
    

    /**
     * Creates new form mild
     */
    public FortuneTelling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbWednesDay = new javax.swing.JRadioButton();
        rdbTuesDay = new javax.swing.JRadioButton();
        rdbThursDay = new javax.swing.JRadioButton();
        rdbFriday = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rdbSaturday = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdbSunday = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        bntSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblLove = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarPer = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        rdbMonDay = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarPerlove = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdbWednesDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbWednesDay.setText("วันพุธ");
        rdbWednesDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbWednesDayActionPerformed(evt);
            }
        });

        rdbTuesDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbTuesDay.setText("วันอังคาร");
        rdbTuesDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTuesDayActionPerformed(evt);
            }
        });

        rdbThursDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbThursDay.setText("วันพฤหัสบดี");
        rdbThursDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbThursDayActionPerformed(evt);
            }
        });

        rdbFriday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbFriday.setText("วันศุกร์");
        rdbFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFridayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("ทำนายดวงความรักตามวันเกิด");

        rdbSaturday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSaturday.setText("วันเสาร์");
        rdbSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSaturdayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("วันเกิด");

        rdbSunday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSunday.setText("วันอาทิตย์");
        rdbSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSundayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("นิสัย");

        bntSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntSubmit.setText("ทำนาย");
        bntSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSubmitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("นิสัยเวลามีความรัก");

        lblLove.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLove.setForeground(new java.awt.Color(255, 0, 0));
        lblLove.setText("0%");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ระดับความครั่งรัก");

        tarPer.setColumns(20);
        tarPer.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        tarPer.setRows(5);
        jScrollPane1.setViewportView(tarPer);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        rdbMonDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbMonDay.setText("วันจันทร์");
        rdbMonDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbMonDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMonDayActionPerformed(evt);
            }
        });

        tarPerlove.setColumns(20);
        tarPerlove.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        tarPerlove.setRows(5);
        jScrollPane2.setViewportView(tarPerlove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbMonDay)
                                    .addComponent(rdbThursDay)
                                    .addComponent(rdbSunday))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntSubmit)
                                    .addComponent(rdbFriday)
                                    .addComponent(rdbTuesDay))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbWednesDay)
                                    .addComponent(rdbSaturday))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLove))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdbMonDay)
                            .addComponent(rdbWednesDay))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbThursDay)
                            .addComponent(rdbSaturday)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbTuesDay)
                        .addGap(18, 18, 18)
                        .addComponent(rdbFriday)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSunday)
                    .addComponent(bntSubmit))
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblLove))
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbWednesDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbWednesDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbWednesDayActionPerformed

    private void rdbTuesDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTuesDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTuesDayActionPerformed

    private void rdbThursDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbThursDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbThursDayActionPerformed

    private void rdbFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFridayActionPerformed

    private void rdbSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSaturdayActionPerformed

    private void rdbSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSundayActionPerformed

    private void bntSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSubmitActionPerformed
        String Per = null, Perlove = null ;
        int num;

        if (rdbMonDay.isSelected()) {
            Per = "ปกติคนที่เกิดวันนี้เป็นคนที่ค่อนข้างแพรวพราว \n" +
            "เป็นคนที่ค่อนข้างจะรักอิสระ ดูเป็นคนเจ้าชู้ไม่รู้ตัว \n" +
            "เพราะเป็นคนมีเสน่ห์ วางตัวดี";
            Perlove = " ถ้ามีความรักขึ้นมาล่ะก็ เหมือนเป็นคนละคน! \n" +
            "จากเสีอตัวใหญ่ พอมีแฟนแล้วจะกลายเป็นแมวน้อย ขี้อ้อน \n" +
            "เอาใจ อยากได้อะไรจัดให้ทุกอย่าง \n" +
            "งอแงกับแฟนเพราะอยากเรียกร้องความสนใจ \n" +
            "ถ้าคบกันแล้วก็อยากให้ดูแล เอาอกเอาใจซึ่งกันและกัน \n" +
            "มือถือนี่ถ้าไม่ล็อกรหัสก็เรียบร้อย! เพราะคนเกิดวันนี้จะแอบหึง \n" +
            "แอบส่องทุกอย่าง แฟนไปไหน ทำอะไร อยู่กับใคร รู้หมด! \n" +
            "แต่คนที่เกิดวันจันทร์ถึงจะมีแฟนยังไงก็ยังไม่ทิ้งเพื่อน ถ้าอีกฝ่ายเข้าใจ \n" +
            "ไม่คิดมากก็คบกันได้ยาว ๆ จ้า";
            lblLove.setText("90%");

        } else if (rdbTuesDay.isSelected()) {
            Per = "คนเกิดวันนี้เป็นพ่อแม่บุญทุ่ม เวลารักใครจะจริงจัง \n" +
            "มากระดับสิบ! ป็นคนใจร้อน ตอบช้า 5 นาทีจะรู้สึกใจหายแล้ว \n" +
            "ว่าเราพูดอะไรผิดไปไหมนะ? หรือว่าเขาไม่อยากคุยกับเราหรือเปล่า? \n" +
            "หรือว่าเกิดเหตุร้ายอะไรขึ้น เอ๊ะ! หรือว่าแอบคุยกับคนอื่น";
            Perlove = "ถ้าอยู่ในช่วงอินเลิฟแล้วจะอารมณ์ดีทั้งวัน ยิ้มคนเดียว \n" +
            "เป็นคนติดแฟน อยากอยู่ด้วยตลอดเวลา เธออยู่ที่ไหน จะไปอยู่ตรงหน้า \n" +
            "จะไปหาแน่ ๆ! และค่อนข้างคาดหวังในตัวคนรักมาก ๆ  \n" +
            "ถ้าให้ 100 ต้องได้กลับมา 100 ชอบอะไรที่แฟร์ ๆ ถ้าไม่แฟร์ก็หาใหม่ \n" +
            "ชอบความตื่นเต้นท้าทาย ถ้าอีกฝ่ายเล่นตัวนิดหน่อย เข้าหาบ้าง เอาใจก่อนบ้าง \n" +
            "แกล้งไม่ตอบบ้าง ยิ่งตื่นเต้น ยิ่งถ้าอีกฝ่ายใส่ใจ และเข้าใจในตัวของคนที่เกิดวันอังคาร \n" +
            "รับรองว่ารักจนมูฟออนไปไหนไม่ได้!";
            lblLove.setText("100%");
        }else if (rdbWednesDay.isSelected()) {
            Per = "คารมดีเป็นที่ 1 ตบมุขโบ๊ะบ๊ะได้ ทันคน \n" +
            "เทคนิคอ่อยชั้นครู แพรวพราวพอ ๆ กับคนเกิดวันจันทร์ \n" +
            "เป็นคนที่ค่อย ๆ ดู ค่อย ๆ เก็บข้อมูลฝ่ายตรงข้าม ไม่วู่วาม \n" + 
            "ชอบนะ แต่ไม่แสดงออกตรง ๆ รอจนกว่าจะแน่ใจจริง ๆ \n" +
            "แล้วถึงจะตกลงเป็นแฟน";
            Perlove = "เป็นคนที่รักใครแล้วรักจริง โรแมนติก เรื่องเล็กๆน้อยก็จำได้ \n" +
            "เอาใจใส่แฟนหรือคนรักมาก แต่ข้อเสียของคนที่เกิดวันนี้ เป็นเพราะอีโก้ที่สูงเสียดฟ้า\n" +
            "อาจจะทำให้เรื่องราวที่มันไม่ได้มีอะไรเลย พังได้ง่ายๆ เพราะความมีอีโก้ของตัวเอง \n" +
            "เวลาโกรธมาก็จะใช้คำพูดที่ไม่ค่อยดี เป็นคนคาดหวังกับความรักสูง คิดมาก ขี้หึง ขี้ระแวง \n" +
            "แล้วพอไม่ได้ตามที่หวัง ก็อาจจะพาลเบื่อได้ง่าย ๆ แนะนำให้ใจเย็น ๆ \n" +
            "และลดความคาดหวังกับอีโก้ลงนิดหน่อย จะทำให้ความรักไปได้ดี";
            lblLove.setText("50%");
        }
        else if (rdbThursDay.isSelected()) {
            Per = "ภายนอกอาจจะดูเป็นคนอ่อยเก่ง แพรวพราว \n" +
            "แต่จริง ๆ แล้วเป็นคนค่อนข้างอ่อนไหว เป็นคนออกจะบ๊องๆ \n" +
            "ขาดๆ เกินๆ ด้วยซ้ำ คนเกิดวันนี้ถึงจะดูอ่อยเก่งก็จริง ดูเป็นสาวฮอต \n" +
            "หนุ่มฮอต แต่รักใครแล้วรักจริงจังมาก ไม่ชอบการนอกใจ และการถูกหักหลัง";
            Perlove = "เวลาคนเกิดวันพฤหัสบดีมีความรักแล้วเหมือนเมากัญชา \n" +
            "อารมณ์ดีทั้งวัน และวันครบรอบ วันเกิด จำได้หมด ตกหลุมรักคนง่าย \n" +
            "ยิ่งถ้าเจอคนที่คุยแบบ Deep Conversation ได้ ยิ่งชอบ ชอบคนที่เป็นผู้ใหญ่ \n" +
            "ยิ่งมีทัศนคติดี ๆ หรือพลังบวก คนที่เกิดวันพฤหัสบดีจะมโนไปถึงขั้นแต่งงานเลย \n" +
            "ทั้งๆ ที่แค่เริ่มคุย แต่ก็ชอบความรักที่ค่อยเป็นค่อยไป ไม่รีบนะ";
            lblLove.setText("60%");
        }else if (rdbFriday.isSelected()) {
            Per = "คนเกิดวันนี้ออกแนวพ่อบ้านใจกล้า ไม่เถียงหรอกนะ \n" +
            "แต่อย่าให้โกรธ! เป็นคนช่างมโน ชอบเพ้อเงียบ ๆ เป็นตุเป็นตะอยู่คนเดียว \n" +
            "และคนเกิดวันนี้เป็นคนอ่อนโยน เอาใจใส่แฟนมาก ต้องการให้แฟนเอาใจใส่ตัวเองเหมือนกัน \n" +
            "ถ้าเจอคนที่ทำให้คนเกิดวันศุกร์รู้สึกรักทั้งแฟน รักทั้งตัวเอง หรือชอบตัวเองตอนอยู่กับแฟน \n" +
            "จะเป็นอะไรที่เพอร์เฟ็กต์มาก";
            Perlove = "ใครชอบคนสายเปย์ มาทางนี้! \n" +
            "คนเกิดวันศุกร์บอกเลยว่าเปย์เก่งงงง ชอบหาอะไรทำ \n" +
            "ชวนแฟนทำนู่น ทำนี่ อยู่ด้วยแล้วไม่มีทางเบื่อแน่นอน \n" +
            "และมักจะเจอคนที่แตกต่างกันที่ อายุ เชื้อชาติ ศาสนา ฐานะ ฯลฯ \n" +
            "แต่ไม่ค่อยสนใจเท่าไร ถ้าพร้อมจะเดินไปด้วยกันก็โอเค คบกันได้ยาวๆ";
            lblLove.setText("85%");
        }else if (rdbSaturday.isSelected()) {
            Per = "คนที่เกิดวันเสาร์ชอบทำตัวเป็นผู้นำ อีโก้สูง บ้าพลัง \n" +
            "ไม่ชอบคนต่อล้อต่อเถียง ฉะนั้นคนที่นิ่ง ๆ สุขุมหน่อยๆ \n" +
            "ก็จะเข้าทางคนที่เกิดวันนี้ เป็นคนเด็ดขาด ชัดเจน ชอบก็คือชอบ \n" +
            "ไม่ยึก ๆ ยัก ๆ ชอบคนเอาใจ ใส่ใจ ชอบอะไรที่เรียบง่าย \n" +
            "มั่นคง ถ้ามีแฟนแล้วก็จะทุ่มสุด ๆ";
            Perlove = "อยากได้อะไรบอกจะจัดให้ตามที่ขอทุกอย่าง ยกเว้นให้ลุงลาออก(เอ๊ย! ไม่ใช่!) \n" +
            "ดูแลแฟนหรือคนรักดีเว่อร์! เหมือนเราเป็นเจ้าหญิงหรือเจ้าชาย แต่ไม่ชอบอะไรที่จุกจิก \n" +
            "ชนิดว่าตามหึงตามจิกเกินเบอร์จะเบื่อมาก แต่ถึงจะไม่ชอบอะไรแบบนั้น \n" +
            "คนที่เกิดวันเสาร์เวลาหึงจะน่ากลัวระดับสิบ!";
            lblLove.setText("70%");
        }else {
            Per = "คนที่เกิดวันอาทิตย์ เขาว่าเป็นคนอารมณ์ขึ้นๆ ลงๆ \n" +
            "อาจจะตามอารมณ์ยากสักหน่อย เป็นคนใจกว้าง ให้อิสระกับคนรัก \n" +
            "แต่ถ้าเข้าโหมดจริงจังแล้วไม่ชอบอะไรเล่นๆ อยู่ไหน ทำอะไรกับใคร \n" +
            "ต้องบอก ต้องรายงาน และถ้าชอบใครก็จะทำทุกวิถีทางเพื่อให้ได้คบ";
            Perlove = "พอมีแฟนแล้วโลกสดใส อะไรก็เป็นสีชมพูไปหมด ถ้ามีแฟนจะขี้บ่นมากๆ \n" +
            "แต่ก็เป็นเพราะรักแหละถึงบ่น เป็นคนรักเดียวใจเดียว คบใครก็คบทีละคน \n" +
            "ไม่ได้หว่านไปทั่วถ้าเทียบกับคนเกิดวันอื่นๆ ถ้าเจอแฟนหรือคนรักที่เข้ากับครอบครัว \n" +
            "หรือเพื่อนได้ก็ผ่านฉลุย เพราะชอบความรักแบบลึกซึ้ง พร้อมที่จะเป็นครอบครัวเดียวกัน \n" +
            "ในอนาคต ชอบคนพูดเพราะ ใส่ใจ ยิ้มหวาน ถ้าสอบผ่านก็จะเสมอต้นเสมอปลายกับคนรักมากๆ";
            lblLove.setText("75%");
        }

        tarPer.setText(" "+Per);
        tarPerlove.setText(" "+Perlove);
    }//GEN-LAST:event_bntSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void rdbMonDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMonDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMonDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortuneTelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortuneTelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortuneTelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortuneTelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FortuneTelling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSubmit;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLove;
    private javax.swing.JRadioButton rdbFriday;
    private javax.swing.JRadioButton rdbMonDay;
    private javax.swing.JRadioButton rdbSaturday;
    private javax.swing.JRadioButton rdbSunday;
    private javax.swing.JRadioButton rdbThursDay;
    private javax.swing.JRadioButton rdbTuesDay;
    private javax.swing.JRadioButton rdbWednesDay;
    private javax.swing.JTextArea tarPer;
    private javax.swing.JTextArea tarPerlove;
    // End of variables declaration//GEN-END:variables
}
