/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miniproject;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SiameseMild extends javax.swing.JFrame {

    /**
     * Creates new form mikl
     */
    public SiameseMild() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnShake = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarResult = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("เสี่ยงเซียมซี");

        btnShake.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnShake.setText("เขย่าเซียมซี");
        btnShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShakeActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Exit");

        tarResult.setColumns(20);
        tarResult.setRows(5);
        jScrollPane1.setViewportView(tarResult);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ผลการทำนาย");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miniproject/278231933_1425132004614652_4739236425392976867_n (1).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnShake)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(215, 215, 215))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShake)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShakeActionPerformed
        String siamese[] = {"ใบเซี่ยมซี่ที่ 19 \nคำทำนายที่สิบเก้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีความร้อนใจด้วยการเจ็บป่วย \n"
            + "แต่ลาภผลน้อย เนื้อคู่ช่วยท่านได้ แต่ความรักอาจจะมีอุปสรรคบ้าง การงานดี ท่านควรหมั่นไหว้พระกวนอิมโพธิสัตว์ \nสิ่งร้ายอาจจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 20 \nคำทำนายที่ยี่สิบ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ ไม่มีอุปสรรค จะทำการใดก็ดีหมด \n"
            + "การงานควรระวัง การมีปากเสียงกับผู้อื่น เจ็บป่วยไม่มี ",
            "ใบเซี่ยมซี่ที่ 21 \nคำทำนายที่ยี่สิบเอ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีโชคลาภและจะมีผู้หใญ่มาคุ้มครอง\n"
            + "การงานเจริญรุ่งเรือง เนื้อคู่อยู่ไม่ไกล เจ็บป่วยจะหายเร็ว สรรพสิ่งสมประสงค์ แต่ควรหมั่นไหว้พระทำบุญสร้างบารมีเอาไว้บ้าง \nเพื่อภายหน้าลูกหลานจะได้ดี เพราะที่ทำเอาไว้",
            "ใบเซี่ยมซี่ที่ 22 \nทำนายที่ยี่สิบสอง เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนต้นไม้ที่กำลังเขียวชะอุ่ม \n"
            + "หมายถึงจะได้ลาภเงินทองไหลมาเทมา การงานจะเจริญก้าวหน้า เนื้อคู่จะเป็นผู้ช่วยให้ท่านเจริญยิ่งขึ้น \nเจ็บป่วยไม่มีสรรพสิ่งสมดังปรารถนาทุกประการดีนักแล",
            "ใบเซี่ยมซี่ที่ 23 \nคำทำนายที่ยี่สิบสาม เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะเกิดถ้วยความให้เกรงสตรี \n"
            + "เป็นศัตรูจงหนัก มิฉะนั้น จะถูกฟ้องหาเพราะชู้เมีย ไม่ควรเดินทางกลางคืน การงานไม่มีอุปสรรค อาจจะเจ็บป่วยเสียเงินทอง \nจึงควรไหว้พระให้ท่านคุ้มครองสิ่งต่าง ๆ อาจกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 24 \nคำทำนายที่ยี่สิบสี่ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้รับความร้อนใจมิฉะนั้นอาจจะมีอันตราย \n"
            + "การงานมีอุปสรรค เจ็บป่วยหายยาก มีบุตรเลี้ยงยาก จงหมั่นไปไหว้เทพเจ้าแห่งชะตาราศรี (ไท่ส่วย-เอี้ย) แล้วทุกสิ่งจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 25 \nคำทำนายที่ยี่สิบห้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ โชคลาภและอำนาจการค้าขายรุ่งเรือง \n"
            + "เจ็บป่วยจะมีหมอดีมารักษา เนื้อคู่อยู่ด้วยกันจะประเสริฐ ท่านจะได้บุตรที่ดี สรรพสิ่งสมประสงค์ดีนักแล",
            "ใบเซี่ยมซี่ที่ 26 \nคำทำนายที่ยี่สิบหก เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีผู้มาให้โชคลาภ การงานอาจจะมีอุปสรรค \n"
            + "เจ็บป่วยหายเร็ว ไม่ช้าจะได้เนื้อคู่ ท่านควรจะหมั่นไหว้พระและเทพเจ้าแห่งโชคลาภ (ใช้ซิ้งเอี้ย) แล้วการค้าจะดี",
            "ใบเซี่ยมซี่ที่ 27 \nคำทำนายที่ยี่สิบเจ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะเสียทรัพย์และของรัก \n"
            + "จงระวังในการเดินทางไกล การค้าไม่มีโชคลาภ เจ็บป่วยหายยาก ท่านควรจะไปไหว้พระและขอพรจากเทพเจ้าแห่งยา \n(หั่วท้อเซียงซือ) แล้วสรรพสิ่งต่าง ๆ จะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 28 \nคำทำนายที่ยี่สิบแปด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนพระอาทิตย์อันร้อนแรง \n"
            + "หมายถึงการงานจะเจริญรุ่งเรือง เจ็บป่วยจะมีหมอดีมารักษา จะมีเนื้อคู่ที่พร้อมด้วยทรัพย์สมบัติ \nสรรพสิ่งที่ขอจะได้สมดังใจหมายแล",
            "ใบเซี่ยมซี่ที่ 29 \nคำทำนายที่ยี่สิบเก้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้จะได้ยศฐาบรรดาศักดิ์ \n"
            + "และสรรพสิ่งลาภจะบริบูรณ์ด้วยทรัพย์สมบัติ การงานเจริญรุ่งเรือง ไม่มีโรคภัยอันตราย ความรักสมหวัง สรรพสิ่งไม่มีอุปสรรคดีนักแล",
            "ใบเซี่ยมซี่ที่ 30 \nคำทำนายที่สามสิบ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ ไม่สมดังใจหมายจะเกิดความร้อนใจ \n"
            + "เจ็บป่วยไข้หายยาก และอาจจะเสียของรักไป ท่านควรจะหมั่นขอพรจากพระกวนอิมโพธิสัตว์ \nและเทพเจ้าแห่งยา(หั่วท้อเซียงซือ) \nสิ่งร้ายจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 31 \nคำทำนายที่สามสิบเอ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ลาภเพราะความฝัน \n"
            + "จะได้ผ้าผ่อนของใช้สอยสรรพสิ่งไม่เหน็ดเหนื่อย การงานไม่มีอุปสรรค อายุยืนยาว จะมีเนื้อคู่และบุตรสุดที่รัก ถ้าเป็นความจะชนะแล",
            "ใบเซี่ยมซี่ที่ 32 \nคำทำนายที่สามสิบสอง เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จักได้ลาภแก้วแหวนเงินทอง \n"
            + "บริบูรณ์ไปด้วยสมบัติการงานก้าวหน้า อนาคตรุ่งเรือง เนื้อคู่มีบุญ อายุยืนยาว สรรพสิ่งสมดังประสงค์ดีนักแล",
            "ใบเซี่ยมซี่ที่ 33 \nคำทำนายที่สามสิบสาม เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนพระอาทิตย์อันร้อนแรง \n"
            + "หมายถึงการงานจะเจริญรุ่งเรือง เจ็บป่วยจะมีหมอดีมารักษา จะมีเนื้อคู่ที่พร้อมด้วยทรัพย์สมบัติ สรรพสิ่งที่ขอจะได้สมดังใจหมายแล",
            "ใบเซี่ยมซี่ที่ 34 \nคำทำนายที่สามสิบสี่ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีการเจ็บป่วยอยู่บ้าง \n"
            + "การค้าขายไม่คล่องตัว โชคลาภยังมีน้อย เนื้อคู่จะช่วยท่านได้ จงหมั่นไหว้พระทำบุญขอพรให้มาก ๆ จะสมปรารถนาทุกประการ",
            "ใบเซี่ยมซี่ที่ 35 \nคำทำนายที่สามสิบห้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ลาภและเนื้อคู่ \n"
            + "การงานไม่มีอุปสรรค เจ็บป่วยจะมีหมอดีมารักษา มิฉะนั้นจะมีผู้ใหญ่คุ้มครอง จงหมั่นไหว้พระขอพรจะดีนักแล",
            "ใบเซี่ยมซี่ที่ 36 \nคำทำนายที่สามสิบหก เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เข้าสู่โชคลาภจะมีผู้สูงอายุมาให้โชค \n"
            + "มิฉะนั้นจะมีเนื้อคู่พร้อมด้วยทรัพย์สมบัติ การค้าขายไม่มีอุปสรรค เจ็บป่วยจะมีหมอดีมารักษา สรรพสิ่งดังใจหมาย ถ้าเป็นความจะชนะแล"};

        tarResult.setText(siamese[new Random().nextInt(siamese.length)]);

    }//GEN-LAST:event_btnShakeActionPerformed
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit ?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }   
    }       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiameseMild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiameseMild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiameseMild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiameseMild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiameseMild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShake;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tarResult;
    // End of variables declaration//GEN-END:variables
}
